# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages


on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    environment:
      name: github-pages
      url: https://etroupe5201.github.io/SE489_Group_Project/templates/home.html  # Fix the URL here
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./templates  # Specify the directory containing your home.html file
          publish_branch: gh-pages
          force_orphan: true 
